version: "3.9"  # optional since v1.27.0
services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - "5062:8080"
    depends_on:
      - redis

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

volumes:
  redis_data:
