version: "3.9"  # optional since v1.27.0
services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - "5062:80"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"

volumes:
  redis_data:
